name: Check for new releases
# on:
#   schedule:
#     - cron:  '0 * * * *'
on:
  push:
    branches:
      - main

jobs:
  check-new-03-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for new holochain releases
        id: check_releases
        run: |
          echo "holochain_version=$(node ./scripts/check-new-03-releases.mjs)" >> $GITHUB_OUTPUT
    outputs:
      holochain-version: ${{ steps.check_releases.outputs.holochain_version }}

  build-03-binaries:
    permissions:
      contents: write
    needs: check-new-03-releases
    if: ${{ needs.check-new-03-releases.outputs.holochain-version }}
    uses: ./.github/workflows/holochain-binaries.yaml
    with:
      holochain-version: ${{ needs.check-new-03-releases.outputs.holochain-version }}


  check-new-04-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for new holochain releases
        id: check_releases
        run: |
          echo "holochain_version=$(node ./scripts/check-new-04-releases.mjs)" >> $GITHUB_OUTPUT
    outputs:
      holochain-version: ${{ steps.check_releases.outputs.holochain_version }}

  build-04-binaries:
    permissions:
      contents: write
    needs: check-new-04-releases
    if: ${{ needs.check-new-04-releases.outputs.holochain-version }}
    uses: ./.github/workflows/holochain-binaries.yaml
    with:
      holochain-version: ${{ needs.check-new-04-releases.outputs.holochain-version }}


  check-new-05-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for new holochain releases
        id: check_releases
        run: |
          echo "holochain_version=$(node ./scripts/check-new-05-releases.mjs)" >> $GITHUB_OUTPUT
    outputs:
      holochain-version: ${{ steps.check_releases.outputs.holochain_version }}

  build-05-binaries:
    permissions:
      contents: write
    needs: check-new-05-releases
    if: ${{ needs.check-new-05-releases.outputs.holochain-version }}
    uses: ./.github/workflows/holochain-binaries.yaml
    with:
      holochain-version: ${{ needs.check-new-05-releases.outputs.holochain-version }}


  check-new-lair-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for new lair releases
        id: check_releases
        run: |
          echo "lair_version=$(node ./scripts/check-new-lair-releases.mjs)" >> $GITHUB_OUTPUT
    outputs:
      lair-version: ${{ steps.check_releases.outputs.lair_version }}

  build-lair-binaries:
    permissions:
      contents: write
    needs: check-new-lair-releases
    if: ${{ needs.check-new-lair-releases.outputs.lair-version }}
    uses: ./.github/workflows/lair-binaries.yaml
    with:
      lair-version: ${{ needs.check-new-lair-releases.outputs.lair-version }}

  check-new-hc-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check for new hc releases
        id: check_releases
        run: |
          echo "hc_version=$(node ./scripts/check-new-hc-releases.mjs)" >> $GITHUB_OUTPUT
    outputs:
      hc-version: ${{ steps.check_releases.outputs.hc_version }}

  build-hc-binaries:
    permissions:
      contents: write
    needs: check-new-hc-releases
    if: ${{ needs.check-new-hc-releases.outputs.hc-version }}
    uses: ./.github/workflows/hc-binaries.yaml
    with:
      hc-version: ${{ needs.check-new-hc-releases.outputs.hc-version }}