name: 'release-hc-binaries'
on:
  workflow_call:
    inputs:
      hc-version:
        required: true
        type: string
jobs:
  publish-hc-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-11, ubuntu-22.04]
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          body: 'holochain_cli (hc) binaries for Linux/Windows/macOS.'
          prerelease: true
          skipIfReleaseExists: true
          tag: hc-binaries-${{ inputs.hc-version }}

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: install Go stable
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: setup binaries (Windows only)
        if: matrix.platform == 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install holochain_cli --version ${{ inputs.hc-version }}
          $HcPath = Get-Command holochain_cli | Select-Object -ExpandProperty Definition
          Copy-Item $HcPath -Destination hc-v${{ inputs.hc-version }}-x86_64-pc-windows-msvc.exe

          gh release upload "holochain-binaries-${{ inputs.hc-version }}" "hc-v${{ inputs.hc-version }}-x86_64-pc-windows-msvc.exe"

      - name: setup binaries (macos only)
        if: matrix.platform == 'macos-11'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install holochain_cli --version ${{ inputs.hc-version }}
          HC_PATH=$(which holochain_cli)
          cp $HC_PATH hc-v${{ inputs.hc-version }}-x86_64-apple-darwin

          gh release upload "holochain-binaries-${{ inputs.hc-version }}" "hc-v${{ inputs.hc-version }}-x86_64-apple-darwin"

      - name: setup binaries (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install holochain_cli --version ${{ inputs.hc-version }}
          HC_PATH=$(which holochain_cli)
          cp $HC_PATH hc-v${{ inputs.hc-version }}-x86_64-unknown-linux-gnu

          gh release upload "holochain-binaries-${{ inputs.hc-version }}" "hc-v${{ inputs.hc-version }}-x86_64-unknown-linux-gnu"
