name: 'release-holochain-binaries-manually'
on:
  push:
    # tags:
    #   - 'holochain-binaries-*'
    branches:
      - release-0.3.0-beta-dev.42-1ddfd2d

jobs:
  publish-holochain-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]
        # platform: [windows-2019, macos-11, ubuntu-22.04]
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v4

      # - id: create-release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     body: 'Holochain binaries for Linux/Windows/macOS.'
      #     prerelease: true
      #     skipIfReleaseExists: true

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: install Go stable
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'


      # - name: Install vcpkg Packages
      #   if: matrix.platform == 'windows-2019'
      #   uses: johnwason/vcpkg-action@v6
      #   id: vcpkg
      #   with:
      #     pkgs: libsodium
      #     triplet: x64-windows-release
      #     token: ${{ github.token }}
      #     github-binarycache: true


      - name: setup binaries (Windows only)
        if: matrix.platform == 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          $env:HOLOCHAIN_VERSION = $(node -p -e "require('./config.json').holochainVersion")
          # $env:SODIUM_LIB_DIR="$(pwd)\vcpkg\packages\libsodium_x64-windows-release\lib"

          cargo install holochain --git https://github.com/matthme/holochain --rev 25b2da432ad0067dcd3099008dc4c2b53a2ba971 --locked
          $HcPath = Get-Command holochain | Select-Object -ExpandProperty Definition
          Copy-Item $HcPath -Destination holochain-v$env:HOLOCHAIN_VERSION-x86_64-pc-windows-msvc.exe

          gh release upload --clobber "holochain-binaries-0.3.0-beta-dev.42-1ddfd2d" "holochain-v$env:HOLOCHAIN_VERSION-x86_64-pc-windows-msvc.exe"

      - name: setup binaries (macos only)
        if: matrix.platform == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          HOLOCHAIN_VERSION=$(node -p -e "require('./config.json').holochainVersion")

          cargo install holochain --git https://github.com/matthme/holochain --rev 25b2da432ad0067dcd3099008dc4c2b53a2ba971 --target aarch64-apple-darwin --locked
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v$HOLOCHAIN_VERSION-aarch64-apple-darwin

          gh release upload "${GITHUB_REF#refs/tags/}" "holochain-v$HOLOCHAIN_VERSION-aarch64-apple-darwin"

      - name: setup binaries (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          HOLOCHAIN_VERSION=$(node -p -e "require('./config.json').holochainVersion")

          cargo install holochain --git https://github.com/matthme/holochain --rev 25b2da432ad0067dcd3099008dc4c2b53a2ba971 --locked
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v$HOLOCHAIN_VERSION-x86_64-unknown-linux-gnu

          gh release upload "${GITHUB_REF#refs/tags/}" "holochain-v$HOLOCHAIN_VERSION-x86_64-unknown-linux-gnu"
