name: 'release-holochain-binaries'
on:
  workflow_call:
    inputs:
      holochain-version:
        required: true
        type: string
      x86_64-pc-windows-msvc:
        required: false
        default: true
        type: boolean
      aarch64-apple-darwin:
        required: false
        default: true
        type: boolean
      x86_64-apple-darwin:
        required: false
        default: true
        type: boolean
      x86_64-unknown-linux-gnu:
        required: false
        default: true
        type: boolean
      aarch64-unknown-linux-gnu:
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      holochain-version:
        required: true
        type: string
      x86_64-pc-windows-msvc:
        required: false
        default: false
        type: boolean
      aarch64-apple-darwin:
        required: false
        default: false
        type: boolean
      x86_64-apple-darwin:
        required: false
        default: false
        type: boolean
      x86_64-unknown-linux-gnu:
        required: false
        default: false
        type: boolean
      aarch64-unknown-linux-gnu:
        required: false
        default: false
        type: boolean

jobs:
  publish-holochain-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2022, macos-latest, macos-13, ubuntu-22.04]
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          body: 'Holochain binaries for Linux/Windows/macOS.'
          prerelease: true
          skipIfReleaseExists: true
          tag: holochain-binaries-${{ inputs.holochain-version }}

      - name: install Rust
        uses: dtolnay/rust-toolchain@1.87.0

      - name: install Go stable
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: setup binaries (x86_64-pc-windows-msvc)
        if: matrix.platform == 'windows-2022' && inputs.x86_64-pc-windows-msvc == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install holochain --version ${{ inputs.holochain-version }} --locked --no-default-features --features sqlite-encrypted,wasmer_sys,backend-go-pion
          $HcPath = Get-Command holochain | Select-Object -ExpandProperty Definition
          Copy-Item $HcPath -Destination holochain-v${{ inputs.holochain-version }}-x86_64-pc-windows-msvc.exe

          CertUtil -hashfile "holochain-v${{ inputs.holochain-version }}-x86_64-pc-windows-msvc.exe" SHA256

          gh release upload "holochain-binaries-${{ inputs.holochain-version }}" "holochain-v${{ inputs.holochain-version }}-x86_64-pc-windows-msvc.exe"

      - name: setup binaries (aarch64-apple-darwin)
        if: matrix.platform == 'macos-latest' && inputs.aarch64-apple-darwin == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rustup target add aarch64-apple-darwin

          cargo install holochain --version ${{ inputs.holochain-version }} --target aarch64-apple-darwin --locked --no-default-features --features sqlite-encrypted,wasmer_sys,backend-go-pion
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v${{ inputs.holochain-version }}-aarch64-apple-darwin

          shasum -a 256 holochain-v${{ inputs.holochain-version }}-aarch64-apple-darwin

          gh release upload "holochain-binaries-${{ inputs.holochain-version }}" "holochain-v${{ inputs.holochain-version }}-aarch64-apple-darwin"

      - name: setup binaries (x86_64-apple-darwin)
        if: matrix.platform == 'macos-13' && inputs.x86_64-apple-darwin == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rustup target add x86_64-apple-darwin

          cargo install holochain --version ${{ inputs.holochain-version }} --target x86_64-apple-darwin --locked --no-default-features --features sqlite-encrypted,wasmer_sys,backend-go-pion
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v${{ inputs.holochain-version }}-x86_64-apple-darwin

          shasum -a 256 holochain-v${{ inputs.holochain-version }}-x86_64-apple-darwin

          gh release upload "holochain-binaries-${{ inputs.holochain-version }}" "holochain-v${{ inputs.holochain-version }}-x86_64-apple-darwin"

      - name: setup binaries (x86_64-unknown-linux-gnu)
        if: matrix.platform == 'ubuntu-22.04' && inputs.x86_64-unknown-linux-gnu == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo install holochain --version ${{ inputs.holochain-version }} --locked --no-default-features --features sqlite-encrypted,wasmer_sys,backend-go-pion
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v${{ inputs.holochain-version }}-x86_64-unknown-linux-gnu

          shasum -a 256 holochain-v${{ inputs.holochain-version }}-x86_64-unknown-linux-gnu

          gh release upload "holochain-binaries-${{ inputs.holochain-version }}" "holochain-v${{ inputs.holochain-version }}-x86_64-unknown-linux-gnu"

      - name: setup binaries (aarch64-unknown-linux-gnu)
        if: matrix.platform == 'ubuntu-22.04' && inputs.aarch64-unknown-linux-gnu == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rustup target add aarch64-unknown-linux-gnu

          # install gcc compiler for aarch64
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu
          sudo apt install g++-aarch64-linux-gnu

          mkdir libsodium
          curl -L --output ./libsodium/LATEST.tar.gz https://github.com/matthme/holochain-binaries/releases/download/libsodium-releases/LATEST.tar.gz
          curl -L --output ./libsodium/LATEST.tar.gz.minisig https://github.com/matthme/holochain-binaries/releases/download/libsodium-releases/LATEST.tar.gz.minisig
          curl -L --output ./libsodium/libsodium-1.0.19-stable.zip https://github.com/matthme/holochain-binaries/releases/download/libsodium-releases/libsodium-1.0.19-stable.zip
          curl -L --output ./libsodium/libsodium-1.0.19-stable.zip.minisig https://github.com/matthme/holochain-binaries/releases/download/libsodium-releases/libsodium-1.0.19-stable.zip.minisig

          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc SODIUM_DIST_DIR="$(pwd)/libsodium" cargo install holochain --version ${{ inputs.holochain-version }} --locked --target aarch64-unknown-linux-gnu --no-default-features --features sqlite-encrypted,wasmer_sys,backend-go-pion
          HOLOCHAIN_PATH=$(which holochain)
          cp $HOLOCHAIN_PATH holochain-v${{ inputs.holochain-version }}-aarch64-unknown-linux-gnu

          shasum -a 256 holochain-v${{ inputs.holochain-version }}-aarch64-unknown-linux-gnu

          gh release upload "holochain-binaries-${{ inputs.holochain-version }}" "holochain-v${{ inputs.holochain-version }}-aarch64-unknown-linux-gnu"
