name: 'release-lair-binaries-manually'
on:
  push:
    tags:
      - 'lair-binaries-*'

jobs:
  publish-lair-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-latest, ubuntu-22.04]
    permissions:
      contents: write
    runs-on: ${{ matrix.platform }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v3

      - id: create-release
        uses: ncipollo/release-action@v1
        with:
          body: 'Lair binaries for Linux/Windows/macOS.'
          prerelease: true
          skipIfReleaseExists: true

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable

      - name: setup binaries (Windows only)
        if: matrix.platform == 'windows-2019'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $env:LAIR_VERSION = $(node -p -e "require('./config.json').lairVersion")

          cargo install lair_keystore --version $env:LAIR_VERSION
          $LkPath = Get-Command lair-keystore | Select-Object -ExpandProperty Definition
          Copy-Item $LkPath -Destination "lair-keystore-v$env:LAIR_VERSION-x86_64-pc-windows-msvc.exe"

          gh release upload "$($env:GITHUB_REF -replace "refs/tags/")" "lair-keystore-v$env:LAIR_VERSION-x86_64-pc-windows-msvc.exe"


      - name: setup binaries (macos only)
        if: matrix.platform == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

          LAIR_VERSION=$(node -p -e "require('./config.json').lairVersion")

          cargo install --version $LAIR_VERSION lair_keystore --target x86_64-apple-darwin
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH lair-keystore-v$LAIR_VERSION-x86_64-apple-darwin

          gh release upload "${GITHUB_REF#refs/tags/}" "lair-keystore-v$LAIR_VERSION-x86_64-apple-darwin"

          cargo install --version $LAIR_VERSION lair_keystore --target aarch64-apple-darwin
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH lair-keystore-v$LAIR_VERSION-aarch64-apple-darwin

          gh release upload "${GITHUB_REF#refs/tags/}" "lair-keystore-v$LAIR_VERSION-aarch64-apple-darwin"

      - name: setup binaries (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LAIR_VERSION=$(node -p -e "require('./config.json').lairVersion")

          cargo install --version $LAIR_VERSION lair_keystore --target x86_64-apple-darwin
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH lair-keystore-v$LAIR_VERSION-x86_64-unknown-linux-gnu

          gh release upload "${GITHUB_REF#refs/tags/}" "lair-keystore-v$LAIR_VERSION-x86_64-unknown-linux-gnu"

          cargo install --version $LAIR_VERSION lair_keystore --target aarch64-apple-darwin
          LAIR_PATH=$(which lair-keystore)
          cp $LAIR_PATH lair-keystore-v$LAIR_VERSION-aarch64-unknown-linux-gnu

          gh release upload "${GITHUB_REF#refs/tags/}" "lair-keystore-v$LAIR_VERSION-aarch64-unknown-linux-gnu"
